---
title: "git_00"
author: "Heydee Martinez"
date: "Spring 2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
Twas brillig, and the slithy toves  
Did gyre and gimble in the wabe:  
All mimsy were the borogoves,  
And the mome raths outgrabe.  
“Beware the Jabberwock, my son!  
  
## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
  
## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
When stretch'd on one's bed  
With a fierce-throbbing head,  
Which precludes alike thought or repose,  
How little one cares  
For the grandest affairs  
That may busy the world as it goes!  

How little one feels  
For the waltzes and reels  
Of our Dance-loving friends at a Ball!  
How slight one's concern  
To conjecture or learn  
What their flounces or hearts may befall.  

How little one minds  
If a company dines  
On the best that the Season affords!  
How short is one's muse  
O'er the Sauces and Stews,  
Or the Guests, be they Beggars or Lords.  

How little the Bells,  
Ring they Peels, toll they Knells,  